import Button from './Button';

export default function PlanResultCard({ plan, studentName }) {
  return (
    <div className="bg-white rounded-lg shadow-lg border-l-4 border-green-500 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-green-50 to-emerald-50 p-6 border-b-2 border-green-200">
        <h3 className="text-2xl font-bold text-green-900 mb-2">✅ {plan.title}</h3>
        <p className="text-sm text-green-700">For {studentName}</p>
      </div>

      {/* Body */}
      <div className="p-6 space-y-6">
        {/* Objectives */}
        <div>
          <h4 className="font-bold text-gray-900 mb-2">🎯 Objectives</h4>
          <p className="text-gray-700 leading-relaxed">{plan.objectives}</p>
        </div>

        {/* Timeline */}
        <div className="grid grid-cols-3 gap-4">
          <div className="bg-blue-50 p-4 rounded-lg">
            <p className="text-xs font-semibold text-blue-600 uppercase">Start Date</p>
            <p className="text-lg font-bold text-blue-900 mt-1">{plan.startDate}</p>
          </div>
          <div className="bg-indigo-50 p-4 rounded-lg">
            <p className="text-xs font-semibold text-indigo-600 uppercase">End Date</p>
            <p className="text-lg font-bold text-indigo-900 mt-1">{plan.endDate}</p>
          </div>
          <div className="bg-green-50 p-4 rounded-lg">
            <p className="text-xs font-semibold text-green-600 uppercase">Status</p>
            <p className="text-lg font-bold text-green-900 mt-1">{plan.status}</p>
          </div>
        </div>

        {/* Milestones */}
        <div>
          <h4 className="font-bold text-gray-900 mb-3">📋 Milestones</h4>
          <ul className="space-y-2">
            {plan.milestones.map((milestone, idx) => (
              <li key={idx} className="flex items-start space-x-3 p-3 bg-gray-50 rounded-lg">
                <input
                  type="checkbox"
                  className="mt-1 w-5 h-5 text-green-600 rounded focus:ring-2 focus:ring-green-500"
                  defaultChecked={false}
                />
                <span className="text-gray-700">{milestone}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* AI Insights (placeholder) */}
        <div className="bg-yellow-50 p-4 rounded-lg border-l-4 border-yellow-400">
          <p className="text-sm font-semibold text-yellow-900 mb-2">🤖 AI Insights</p>
          <p className="text-sm text-yellow-800">
            This plan was generated by analyzing the student's profile, learning goals, and recent research insights. Regular progress check-ins are recommended.
          </p>
        </div>
      </div>

      {/* Footer */}
      <div className="bg-gray-50 px-6 py-4 flex gap-2 border-t border-gray-200">
        <Button variant="success" size="sm">Save Plan</Button>
        <Button variant="outline" size="sm">Edit</Button>
        <Button variant="secondary" size="sm">Download PDF</Button>
      </div>
    </div>
  );
}

